#ifndef __TYPES_GENERIC_H__
#define __TYPES_GENERIC_H__

typedef enum tag_draw_type {

    DRAW_UNKNOWN,

    DRAW_STUFF_BEGIN,
        DRAW_SKIP,
    DRAW_STUFF_END,

    DRAW_START,

    DRAW_PENDING,

    DRAW_PATH_BEGIN,
        DRAW_PATH_RIVER,
        DRAW_PATH_MOTORWAY,
        DRAW_PATH_TRUNK,
        DRAW_PATH_PRIMARY,
        DRAW_PATH_SECONDARY,
        DRAW_PATH_TERTIARY,
        DRAW_PATH_ROAD,
        DRAW_PATH_FOOTWAY,
        DRAW_PATH_TREEROW,
        DRAW_PATH_RAILWAY,
        DRAW_PATH_BRIDGE,
        DRAW_PATH_TUNNEL,
    DRAW_PATH_END,

    DRAW_BUILDING_BEGIN,
        DRAW_BUILDING,
        DRAW_BUILDING_OUTER,
        DRAW_BUILDING_INNER,
    DRAW_BUILDING_END,

    DRAW_AREA_BEGIN,
        DRAW_AREA_UNKNOWN,
        DRAW_AREA_WATER,
        DRAW_AREA_ASPHALT,
        DRAW_AREA_GRASS,
        DRAW_AREA_FORSET,
        DRAW_AREA_SAND,
        DRAW_AREA_MOUNTAIN,
        DRAW_AREA_STONE,
    DRAW_AREA_END,

    DRAW_REL_BEGIN,
        DRAW_REL_STREET,
        DRAW_REL_WATERWAY,
        DRAW_REL_BRIDGE,
        DRAW_REL_TUNNEL,
    DRAW_REL_END,

    DRAW_WATER,

    DRAW_LAST_ID
}   draw_type_t;

#endif
